server:
  port: 8090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/momozzi?useSSL=false
    username: momozzi
    password: momozzi
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  web:
    resources:
      static-locations: classpath:/recipeimgs/

image:
  add-resource-locations: /recipeimgs/
  add-resource-handler: /recipeimgs/**

  image-dir: /recipeimgs/
  image-url: http://localhost:8090/recipeimgs/

jwt:
  secret: dW5pLXJlYWN0LW5naW54LXNwcmluZy1ib290LWp3dC1vcmFjbGUtZG9ja2VyLWVjMi1yZWFjdC1uZ25peC1zcHJpbmctYm9vdC1qd3Qtb3JhY2xlLWRvY2tlci1lYzIK

mybatis:
  mapper-locations: mybatis/mapper/*.xml
  type-aliases-package: com.oh.momozzi
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: info